# erpnext-nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: erpnext-nginx
  labels:
    app.kubernetes.io/name: erpnext-nginx
    app.kubernetes.io/instance: erpnext
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: erpnext
